locals:
  hosts:
    my_host:
      ansible_host: localhost
      ansible_connection: local
aws_hosts:
  hosts:
    main_server:
      ansible_host: "{{ main_server_host }}"
      ansible_user: "{{ main_server_user }}"
      ansible_password: "{{ main_server_pass }}"
    dividend_server:
      ansible_host: "{{ dividend_server_host }}"
      ansible_user: "{{ dividend_server_user }}"
      ansible_password: "{{ dividend_server_pass }}"
office_internal_hosts:
  hosts:
    joshkile_server:
      ansible_connection: ssh
      ansible_host: "{{ joshkile_server_host }}"
      ansible_user: "{{ joshkile_server_user }}"
      ansible_password: "{{ joshkile_server_pass }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    nate_server:
      ansible_connection: ssh
      ansible_host: "{{ nate_server_host }}"
      ansible_user: "{{ nate_server_user }}"
      ansible_password: "{{ nate_server_pass }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ronnie_server:
      ansible_connection: ssh
      ansible_host: "{{ ronnie_server_host }}"
      ansible_user: "{{ ronnie_server_user }}"
      ansible_password: "{{ ronnie_server_pass }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
