---
- name: Initial Installation
  hosts: my_host
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Install SSHPASS
      apt:
        name: sshpass
        state: present
    # - name: Creating Directory for Project
    #   file:
    #     path: /home/project24
    #     state: directory