---
- hosts: my_host
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Add Node.js repository
      shell: curl -fsSL https://deb.nodesource.com/setup_21.x | bash -
    - name: Install Node.js
      apt:
        name: nodejs
        state: present
