# before running this template please copy and paste the content from README file first -> /home/ansible-config/pm2/ecosystem.config.js

---
- hosts: my_host
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: PM2 Installation
      shell: npm i -g pm2
    - name: Copy ecosystem.config.js
      copy:
        src: /home/ansible-config/pm2/ecosystem.config.js
        dest: /home/project24
